PROGRAM MAIN
  ! test various subroutines
  USE KEYS
  USE NETWORKUTIL
  USE GENUTIL
  
  IMPLICIT NONE
  TYPE(NETWORK), TARGET :: NET
  TYPE(NETWORK), POINTER :: NETP
  
  NETP=>NET

  CALL READKEY

!  CALL TESTREDISTRIBFLOW
!  CALL TESTGETFLOW
!  CALL TESTMESHDYNAMICS

!  CALL TESTSMALL
  
!  CALL TESTMESH
!  CALL TESTPLACECONT
CALL TESTCONTNODES
!  CALL TESTJUMPNODE
!  CALL TESTREADNETWORK
  
 
CONTAINS
  SUBROUTINE TESTCONTnodes
    ! test node contraction updates
    USE NODECONTRACTUTIL
    IMPLICIT NONE
    INTEGER :: CC, NC
    DOUBLE PRECISION, ALLOCATABLE :: NODEFLOW(:)

    ! set up network structure
    CALL NETWORKFROMFILE(NETP,NETFILE)
    
    CALL INITIALIZE_NodeCONTRACT(NETP,NCONT)

    PRINT*, 'Contraction nodes and volumes:'
    DO CC = 1,NETP%NCONT
       PRINT*, CC, NETP%CONTNODES(CC,:), NETP%NODEVOLS(NETP%CONTNODES(CC,:))
    ENDDO

    
    ALLOCATE(NODEFLOW(NETP%NNODE))
    CALL NODECONTRACTUPDATE(NETP,1D0,0.1D0,2D0,NODEFLOW)

    PRINT*, 'Contraction nodes and volumes, updated:'
    DO CC = 1,NETP%NCONT
       PRINT*, CC, NETP%CONTNODES(CC,:), NETP%NODEVOLS(NETP%CONTNODES(CC,:))
    ENDDO

    print*, 'Node flows:'
    DO NC = 1,NETP%NNODE
       PRINT*, NC, NODEFLOW(NC)
       ENDDO

    
    CALL CLEANUPNETWORK(NETP)
    DEALLOCATE(NODEFLOW)
  END SUBROUTINE TESTCONTNODES
  
  SUBROUTINE TESTSMALL
    ! test small functions
    USE GENUTIL
    IMPLICIT NONE

    INTEGER :: LIST(10)
    INTEGER, PARAMETER :: NPICK=5
    INTEGER :: I, VALS(NPICK), INDS(NPICK)
    
    LIST = (/(I, I=1,10)/)*2

    PRINT*, LIST

    
    CALL RANDSELECT_INT(LIST,NPICK,.true.,VALs,INDs)
    DO I = 1,NPICK
       PRINT*, I,  INDS(I), VALS(I)
    ENDDO
    
  END SUBROUTINE TESTSMALL
  
  SUBROUTINE TESTMESH
    USE MESHUTIL
    
    ! test mesh setup and output
    IMPLICIT NONE
    DOUBLE PRECISION, ALLOCATABLE :: FIELDS(:,:,:)
    TYPE(MESH), TARGET :: MESHOBJ
    TYPE(MESH), POINTER :: MESHP
    INTEGER :: CT, IND
    
    MESHP=>MESHOBJ

    ! set up network structure
    CALL NETWORKFROMFILE(NETP,NETFILE)
    
    ! set up mesh
    CALL SETUPNETWORKMESH(MESHP,NETP,MAXMESHSIZE,MINMESHPT)

    DO CT = 1, MESHP%NCELL
       IF (MESHP%CELLTYPE(CT).EQ.0) THEN
          IND = MESHP%NODEIND(CT)
       ELSE
          IND = MESHP%EDGEIND(CT,1)
       ENDIF
       PRINT*, CT, MESHP%CELLTYPE(CT), IND, MESHP%POS(CT,:), MESHP%BOUNDS(CT,:), MESHP%LEN(CT)
    ENDDO
    
    ! ! make a field on the mesh
    ! ALLOCATE(FIELDS(NETP%MESHDIM1, NETP%NEDGE,1))
    ! FIELDS = 0D0
    ! FIELDS(2:NETP%NMESH(3)-1,3,1) = 2D0
    
    ! output mesh
    print*, 'outputting to file:', meshfile
    CALL OUTPUTMESH(MESHP,MESHFILE)

 !   DEALLOCATE(FIELDS)
    CALL CLEANUPMESH(MESHP)
  END SUBROUTINE TESTMESH
  

  SUBROUTINE TESTREADNETWORK
    ! test placing of contractions
    IMPLICIT NONE
    INTEGER :: LC

    ! set up network structure
    CALL NETWORKFROMFILE(NETP,NETFILE)

    DO LC = 1,NETP%NLOOP
       PRINT*, LC, NETP%LOOPEDGES(LC,1:NETP%LOOPLENS(LC))
    ENDDO

  END SUBROUTINE TESTREADNETWORK
  
END PROGRAM MAIN
